image: python:3.12-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --editable .[dev]


lint:
  script:
    - ruff check

test:
  script:
    - pytest

type:
  script:
    - mypy satplot