image: $CI_REGISTRY/msl/libraries/spherapy:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --editable .[dev]


lint:
  script:
    - ruff check

test:
  image: "python:$VERSION-slim"
  script:
    - export SPHERAPY_CONFIG_DIR='.'
    - pytest
  parallel:
    matrix:
      - VERSION: ['3.10','3.11','3.12']

type:
  script:
    - mypy spherapy --disable-error-code=import-untyped